FROM maven:3.8.5-openjdk-17-slim
RUN apt-get update && apt-get install -y docker.io docker-compose && rm -rf /var/lib/apt/lists/*
RUN useradd -m -s /bin/bash maven
RUN usermod -aG docker maven
USER maven
WORKDIR /home/maven