version: '3.8'
services:
  employee-service:
    image: royalborg/employee-service:${BUILD_NUMBER}
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/emsdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=yourpassword
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - ems-network
  department-service:
    image: royalborg/department-service:${BUILD_NUMBER}
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/deptdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=yourpassword
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - ems-network
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=emsdb
      - MYSQL_DATABASE=deptdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ems-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - ems-network
networks:
  ems-network:
    driver: bridge
volumes:
  mysql-data: